#10 [ui] detail / 책 상세 뷰 구현
SOPT-TEAM6-Aladin/Aladin-AOS pull request #16
Opened 2022-11-17 19:17 UTC by b1urrrr

## 관련 이슈
- closed #10 

## 작업한 내용
- 책 상세 뷰 xml 구현

## PR 포인트
- 이미지 버튼 touch target으로 패딩을 6dp씩 줬어요
- 네이밍 잘못한 애들 있으면 알려주세요 (특히 shape)
- 더보기 버튼은 그냥 LinearLayout으로 만들었는데 더 나은 컴포넌트가 있다면 알려주세요

2022-11-18 13:03 UTC, Cat-JiYoung approved these changes
수고하셨습니다👍👍

2022-11-21 13:37 UTC, 2zerozu requested changes
gradlew, gradlew.bat 포함해서 제가 리뷰 달아둔 것들 지워지면 안 될 것 같아요!
그리고 네이밍이랑 컬러값, 소수점, 텍스트스타일 위주로 리뷰해드렸네요
나중에 로직부분 올라오면 더 자세히 리뷰하겠숨다ㅏ
뷰 코드 길이 보니까 고생한 게 눈에 훤하네요ㅠㅠ 작업하느라 고생했습니다ㅏ

+) LinearLayout이 최선으로 보입니다 :)

2022-11-21 13:37 UTC, 2zerozu commented on .github/ISSUE_TEMPLATE/issue-template.md
> -- [ ] 작업할 내용
이거 지우면 안 되는데요!!!

2022-11-21 13:37 UTC, 2zerozu commented on .github/pull_request_template.md
> --
이거도!! 아ㅏ내가 깃 이그노어 잘못 설정했나 ...

2022-11-21 13:37 UTC, 2zerozu commented on .gitignore
> -# End of https://www.toptal.com/developers/gitignore/api/android,androidstudio,kotlin,java,macos,windows
이거도..

2022-11-21 13:37 UTC, 2zerozu commented on .idea/.gitignore
> -/workspace.xml
이거도ㅠㅠ

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailActivity.kt
> +}
나중에 작업할 때 BindingActivity 상속받아서 작업해주세요!

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/drawable/shape_blue_line_12_rect.xml
> +        android:width="1.9dp" />
소수점이 있네요

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/drawable/shape_g1_fill_12_rect.xml
> +    <corners android:radius="11.6dp" />
여기도 소수점이 있네요
디자이너와 이야기해서 조율해주세요

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/drawable/shape_gray_topline_rect.xml
> +                android:color="#eaeaea" />
컬러 알파값 말고 속성 추가해서 사용해주세용
없으면 디자이너한테 컬러값 정해달라고 하면 됩니다

+) 파일명 topline보단 line으로 쓴다면 겹치는 거 같이 쓸 수 있을 것 같아요

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/drawable/shape_white_fill_shadow_rect.xml
> +</layer-list>
헉 shadow 혹시 `elevation`으로 사용 불가능한가요??

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/values/colors.xml
> +    <color name="nothing">#00000000</color>
혹시 black이라면 `#000000`으로 설정해주세요 그리고 디자이너가 컬러값 지정해주지 않았다면 black이 더 좋을 것 같아요

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            android:id="@+id/layout_detail_scroll"
`ll_detail_scroll`이 좋을 것 같네요!

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +        app:layout_constraintBottom_toTopOf="@id/toolbar_detail_bottom"
음 이해가 잘 안 되는데 제약을 이렇게 준 이유를 알 수 있을까요??

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:id="@+id/toolbar_detail"
`tb_detail`

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                    android:background="#eaeaea"
알파값!!

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                    android:textSize="14sp"
fontFamily랑 textSize말고 textAppearance 사용해주세용

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                    android:background="#eaeaea"
알파ㅏ

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                    android:textSize="14sp"
textAppearance 만약 없다면 디자이너한테 얘기해주세요!

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                    android:textSize="12sp"
textAppearance

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                    android:id="@+id/btn_detail_more_intro"
네이밍 btn보다는 ll이 좋을 것 같아요
그래두 버튼속성은 아니니까 ..?

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:id="@+id/layout_detail_book_info"
cl_detail~~

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:id="@+id/layout_detail_index"
cl_detail~~

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:id="@+id/layout_detail_summary"
cl~~

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:id="@+id/layout_detail_review"
cl~~

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                        android:layout_marginTop="25.2dp"
소수점이 있네요

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                            android:text="4.6" />
string 추가해서 사용해주세용

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                            android:text="/ 5.0" />
얘두

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                        android:layout_marginBottom="25.2dp"
소수점

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                    android:layout_marginTop="15.6dp"
소수점

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:layout_marginHorizontal="3.5dp"
소수점

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:background="#eaeaea" />
알파값

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +                android:layout_marginTop="23.5dp">
소수점

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +        android:id="@+id/toolbar_detail_bottom"
tb

2022-11-21 13:37 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +            android:id="@+id/layout_detail_purchase"
ll

2022-11-23 06:44 UTC, b1urrrr commented on .github/ISSUE_TEMPLATE/issue-template.md
> -- [ ] 작업할 내용
제가 캐시 지우고 나서 untracked 파일들은 커밋을 안 했더니 지워진 것 같아요 😅
`.github/*`, `.gitignore` 다 올려놓을게요!

2022-11-23 06:48 UTC, b1urrrr commented on app/src/main/res/drawable/shape_gray_topline_rect.xml
> +                android:color="#eaeaea" />
선이 top에만 있어서 top을 붙여봤는데 혹시 상하좌우에 선이 있는 경우랑 헷갈리진 않을까요?

2022-11-23 06:50 UTC, b1urrrr commented on app/src/main/res/values/colors.xml
> +    <color name="nothing">#00000000</color>
투명한 색입니다!
제가 ImageButton background 등에 투명한 색을 쓰는 경우가 많아서 넣어놨는데 네이밍이 애매한 것 같기도 하네요...
어떻게 하는 게 좋을까요?

2022-11-23 06:52 UTC, b1urrrr commented on app/src/main/java/com/sopt/aladinaos/presentation/detail/DetailActivity.kt
> +}
넵!

2022-11-23 07:03 UTC, b1urrrr commented on app/src/main/res/drawable/shape_white_fill_shadow_rect.xml
> +</layer-list>
`elevation` 할 수 있어요!! `elevation`으로 바꿀까요?

2022-11-23 07:07 UTC, b1urrrr commented on app/src/main/res/layout/activity_detail.xml
> +        app:layout_constraintBottom_toTopOf="@id/toolbar_detail_bottom"
<img src="https://user-images.githubusercontent.com/70993562/203488949-774a9eef-7ca9-48b8-81ab-c680c29b0246.gif" width=30% height=30%>

하단 툴바 위로만 스크롤뷰가 보여서 이렇게 제약을 설정해봤는데
`layout_constraintBottom_toBottomOf="parent"`로 하고 하단 padding 값을 주는 게 더 나을까요...?

2022-11-23 07:29 UTC, b1urrrr commented on app/src/main/res/drawable/shape_blue_line_12_rect.xml
> +        android:width="1.9dp" />
다 반올림할게요!
소수점을 지양한다는 것도 처음 알았네요... 감사합니다!

2022-11-23 07:52 UTC, b1urrrr commented on app/src/main/res/layout/activity_detail.xml
> +            android:id="@+id/layout_detail_scroll"
넹~ 노션도 수정해놓을게요!

2022-11-23 08:16 UTC, b1urrrr commented on app/src/main/res/layout/activity_detail.xml
> +                    android:background="#eaeaea"
디자이너님께 요청드려서 color 값으로 바꾸겠습니다!! 감사해요~

2022-11-23 08:26 UTC, 2zerozu commented on app/src/main/res/drawable/shape_gray_topline_rect.xml
> +                android:color="#eaeaea" />
> 선이 top에만 있어서 top을 붙여봤는데 혹시 상하좌우에 선이 있는 경우랑 헷갈리진 않을까요?

오 그건 몰랐네 topline 고고

2022-11-23 08:27 UTC, b1urrrr commented on app/src/main/res/layout/activity_detail.xml
> +                            android:text="4.6" />
넵!

2022-11-23 08:27 UTC, 2zerozu commented on app/src/main/res/drawable/shape_white_fill_shadow_rect.xml
> +</layer-list>
> `elevation` 할 수 있어요!! `elevation`으로 바꿀까요?

가능하면 그게 좋을 것 같아요
커스텀 그림자 경우에는 만들어서 하는 게 좋지만?!

2022-11-23 08:30 UTC, 2zerozu commented on app/src/main/res/values/colors.xml
> +    <color name="nothing">#00000000</color>
> 투명한 색입니다!
> 
> 제가 ImageButton background 등에 투명한 색을 쓰는 경우가 많아서 넣어놨는데 네이밍이 애매한 것 같기도 하네요...
> 
> 어떻게 하는 게 좋을까요?

`android:background="@null"`짠

2022-11-23 08:31 UTC, 2zerozu commented on app/src/main/res/layout/activity_detail.xml
> +        app:layout_constraintBottom_toTopOf="@id/toolbar_detail_bottom"
> <img src="https://user-images.githubusercontent.com/70993562/203488949-774a9eef-7ca9-48b8-81ab-c680c29b0246.gif" width=30% height=30%>
> 
> 
> 
> 하단 툴바 위로만 스크롤뷰가 보여서 이렇게 제약을 설정해봤는데
> 
> `layout_constraintBottom_toBottomOf="parent"`로 하고 하단 padding 값을 주는 게 더 나을까요...?

아 ~~ 툴바가 바텀에 있구나 확인이용

2022-11-23 08:42 UTC, b1urrrr commented on app/src/main/res/drawable/shape_white_fill_shadow_rect.xml
> +</layer-list>
넹~

2022-11-23 08:50 UTC, b1urrrr commented on app/src/main/res/values/colors.xml
> +    <color name="nothing">#00000000</color>
😮

2022-11-23 10:56 UTC, b1urrrr commented on app/src/main/res/drawable/shape_white_fill_shadow_rect.xml
> +</layer-list>
아앗.. 상단에 elevation으로 그림자 넣는 방법을 모르겠네요 🥲

2022-11-23 11:37 UTC, b1urrrr commented
@2zerozu elevation 빼고 다 수정했습니다! 
잘 했는지 한번만 확인해주세요😙

2022-11-23 14:34 UTC, 2zerozu approved these changes
LGTM ^___^

2022-11-23 14:55 UTC, merged