#11 [ui] home / 홈 프래그먼트 구현
SOPT-TEAM6-Aladin/Aladin-AOS pull request #20
Opened 2022-11-23 12:49 UTC by Cat-JiYoung

## 관련 이슈
- closed #11 

## 작업한 내용
- 홈 뷰 xml 구현

## PR 포인트
- toolbar에 있는 검색창 width가 더 길어야될 것 같은데 이것저것 해보는데도 잘 안되네용,,constraint를 잘 못 준건지 확인 부탁드립니다
- 네이밍 컨벤션에 안맞는 부분들 있으면 알려주세요(drawable 파일명 포함)

2022-11-23 14:44 UTC, 2zerozu requested changes
고생하셨습니다!
width, height는 특정 dp로 값을 지정하지 않습니다요
최대한 wrap, match, 0dp 이용해봅시다!!

+ 불필요한 들여쓰기는 지양해주십쇼!!

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/AndroidManifest.xml
> +</manifest>
줄 수 하나 줄여야할듯?!

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/drawable/shape_home_search.xml
> +</shape>
이건 무슨 파일인가요??

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/drawable/ic_toolb_home_barcode.xml
> +</vector>
혹시 home에서만 쓰이는 아이콘이라면 ic_home_toolb~가 좋긴 할 것 같은데 딱히 겹칠 일은 없을 것 같아서 괜찮을 것 같기도?!

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/layout/item_home_editor_choice.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
```suggestion
    </FrameLayout>
</androidx.constraintlayout.widget.ConstraintLayout>
```

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/layout/item_home_editor_choice.xml
> +        android:layout_height="204dp">
제약 + 마진or패딩으로 해결하는 게 좋을 것 같아요
width, height는 보통 wrap_content, match_parent, 0dp 써서유

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/layout/item_home_topseller.xml
> +        android:scaleType="fitXY"
이거 아직 이미지 안 들어와서 이렇게 준 걸까요?

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/layout/item_home_topseller.xml
> +        android:layout_height="0dp"
width를 116으로 준 이유가 있을까요?

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/layout/item_home_topseller.xml
> +        android:layout_height="0dp"
이친구도요!

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
```suggestion
```

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/values/strings.xml
>  </resources>
```suggestion
    <string name="home_aladin_made_goods">알라딘이 만든 사은품</string>
</resources>
```

2022-11-23 14:44 UTC, 2zerozu commented on app/src/main/res/layout/item_home_topseller.xml
> +    <ImageView
```suggestion
    android:layout_height="wrap_content">

    <ImageView
```

2022-11-23 15:29 UTC, b1urrrr requested changes
고생하셨습니다 👍
제가 머지한 코드가 있어서 develop 풀 받고 충돌 해결도 부탁드려용

2022-11-23 15:29 UTC, b1urrrr commented on app/src/main/res/layout/item_home_editor_choice.xml
> +            tools:srcCompat="@tools:sample/avatars" />
아마 서버에서 background, thumbnail 합친 하나의 이미지로 넘겨줄 거예요!
ImageView 하나만 남겨놔도 될 것 같습니다

2022-11-23 15:29 UTC, b1urrrr commented on app/src/main/res/drawable/shape_home_search.xml
> +</shape>
[노션에 있는 drawable 컨벤션](https://www.notion.so/drawable-file-name-2ab512b0de8d493a862eb92bcadad9e9#db07f794f270457ab6849c8d761aa494) 참고해서 파일명 수정하면 좋을 것 같아요!
예) shape_home_g5_fill_12_rect.xml

2022-11-23 15:29 UTC, b1urrrr commented on app/src/main/res/layout/item_home_editor_choice.xml
> +            tools:srcCompat="@tools:sample/avatars" />
그리고 [컨벤션](https://www.notion.so/xml-id-f0c5fbbf124f49429b3b7e5034f38311) 맞게 네이밍하면 좋을 것 같아용

2022-11-24 07:20 UTC, Cat-JiYoung commented on app/src/main/res/drawable/shape_home_search.xml
> +</shape>
toolbar 검색창 배경을 구현한건데 아래 채연이 리뷰처럼 컨벤션 맞춰서 파일명 수정하겠습니다!

2022-11-24 07:21 UTC, Cat-JiYoung commented on app/src/main/res/drawable/ic_toolb_home_barcode.xml
> +</vector>
오홍 그래도 혹시 모르니 파일명 수정하겠습니당

2022-11-24 07:28 UTC, Cat-JiYoung commented on app/src/main/res/layout/item_home_topseller.xml
> +        android:scaleType="fitXY"
넵 근데 어차피 이미지 받아오는거면 처음부터 width는 match, height는 wrap으로 해도 되는건가요?

2022-11-24 07:32 UTC, Cat-JiYoung commented on app/src/main/res/layout/item_home_topseller.xml
> +        android:layout_height="0dp"
wrap이나 match로 줬을때 디자인에 나와있는대로 줄바꿈이 안되더라구요,,,제가 constraint를 처음부터 잘못한걸까요?ㅠㅠ

2022-11-24 07:44 UTC, Cat-JiYoung commented on app/src/main/res/layout/item_home_editor_choice.xml
> +            tools:srcCompat="@tools:sample/avatars" />
넵 컨벤션 수정하겠습니다:) thumbnail만 삭제했습니다! background_trans까지 삭제하면 글씨들이 흰색이라 안보이더라구요,,

2022-11-24 07:47 UTC, Cat-JiYoung commented on app/src/main/res/drawable/shape_home_search.xml
> +</shape>
넵 수정했어요 감사합니다!

2022-11-24 08:15 UTC, b1urrrr approved these changes
LGTM 😊👍

2022-11-24 15:36 UTC, 2zerozu commented on app/src/main/res/layout/item_home_topseller.xml
> +        android:scaleType="fitXY"
> 넵 근데 어차피 이미지 받아오는거면 처음부터 width는 match, height는 wrap으로 해도 되는건가요?

네네 wrap wrap해도 될겁니다요

2022-11-24 15:36 UTC, 2zerozu commented on app/src/main/res/layout/item_home_topseller.xml
> +        android:layout_height="0dp"
> wrap이나 match로 줬을때 디자인에 나와있는대로 줄바꿈이 안되더라구요,,,제가 constraint를 처음부터 잘못한걸까요?ㅠㅠ

제약을 다시 줘보는 게 좋을 것 같네요잉

2022-11-25 12:49 UTC, 2zerozu approved these changes
고생하셨습니다!!

2022-11-25 13:43 UTC, closed without merging